### ISSUE TITLE
パス(ファイル名)の誤り

### ISSUE THREAD

**Issue by vinyl-umbrella** [ca-risken/doc#126]
`docs/risken/quick_start.md` のドメインのデータソースを設定する説明にて，`/osint/domain_datasource/` に遷移するとファイルが存在しないため，404になります．

https://github.com/ca-risken/doc/blob/db183539a85e5c42b46505e201b202e1eea5e73f/docs/risken/quick_start.md?plain=1#L25

`docs/osint/datasource.md` は存在するため，そちらが本来のパスとなりそうですがいかがでしょうか？

ファイル名を修正すべきなのかリンクのパスを修正すべきか判断つかなかったため，PRではなくIssueとしてあげさせていただきました．

**Comment by gassara-kys** [comment]
@vinyl-umbrella ご指摘ありがとうございます。こちら修正します 🙏

**Comment by gassara-kys** [comment]
@vinyl-umbrella こちら修正致しましたのでクローズさせて頂きます。
何かありましたら、またよろしくお願い致します。
https://docs.security-hub.jp/risken/quick_start/
